### 최종실습 
- 영화 데이터 평점 분석

In [4]:
import numpy as np

In [5]:
# 데이터 불러오기
data = np.genfromtxt('./data/ratings.dat',delimiter='::').astype("int64")
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [3]:
# user_id , item_id  rating , timestamp(유닉스타임스탬프변환기사용하면시간변경가능)

In [6]:
# 배열의 차원 크기,전체요소 갯수 
print('차원: ',data.ndim)
print('크기: ',data.shape)
print('전체요소갯수: ',data.size)
print('타입: ',data.dtype)

차원:  2
크기:  (1000209, 4)
전체요소갯수:  4000836
타입:  int64


In [7]:
# 전체 평점 평균 구하기
# 평균--> rating(몇번 열인지 잘 고민)
data[:,2]  # 전체 평점
data[:,2].mean()  # 2:은 안됨
np.mean(data[:,2])

3.581564453029317

In [8]:
# np.unique()--> 데이터의 고유값을 구하는 함수
user_id = np.unique(data[:,0])
print(user_id)
print(user_id.size)
print(user_id.shape)
user_id

[   1    2    3 ... 6038 6039 6040]
6040
(6040,)


array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [82]:
# 사용자 아이디만 블리언 인덱싱하기
# --> 우선 아이디가 1번인 사람만 추출해보자
data[data[:,0]==1]


array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [84]:
# 위에서 구한 사용자 아이디가 1인 데이터의 평점 평균 구하기
np.mean(data[data[:,0]==1][:,2])

4.188679245283019

In [115]:
# 사용자별 평균 평점 구하기
#  내 방법
for i in user_id :
    #rs = np.mean(data[data[:,0]==i][:,2])
    rs = data[data[ : , 0 ] == i][:, 2].mean()
    rs2 = np.array([i,rs])
    print(rs2)

[1.         4.18867925]
[2.         3.71317829]
[3.         3.90196078]
[4.         4.19047619]
[5.         3.14646465]
[6.         3.90140845]
[7.         4.32258065]
[8.         3.88489209]
[9.         3.73584906]
[10.          4.11471322]
[11.          3.27737226]
[12.          3.82608696]
[13.          3.38888889]
[14.    3.32]
[15.          3.32338308]
[16.          3.02857143]
[17.          4.07582938]
[18.          3.64918033]
[19.          3.57254902]
[20.          4.08333333]
[21.          2.90909091]
[22.          3.06734007]
[23.          3.31578947]
[24.          3.94852941]
[25.          3.74117647]
[26.    2.96]
[27.          4.17142857]
[28.          3.75700935]
[29.          3.58333333]
[30.          3.48837209]
[31.          3.73109244]
[32.     3.625]
[33.          3.49872123]
[34.          3.86585366]
[35.          3.54040404]
[36.         4.1994302]
[37.          3.69811321]
[38.    3.58]
[39.          3.56451613]
[40.          3.44791667]
[41.    3.48]
[42.        

[320.           4.23809524]
[321.           3.26126126]
[322.     4.45]
[323.           3.78813559]
[324.           3.32894737]
[325.           4.04651163]
[326.           3.33509235]
[327.           3.66949153]
[328.           3.03225806]
[329.           2.72643979]
[330.           4.01315789]
[331.           3.76541096]
[332.           4.28358209]
[333.           3.35242291]
[334.           3.95081967]
[335.    2.5]
[336.           4.30841121]
[337.           3.52525253]
[338.           3.66574586]
[339.           4.02419355]
[340.           3.52777778]
[341.    4.2]
[342.           3.69105691]
[343.           4.04713805]
[344.           2.95555556]
[345.    4.4]
[346.           4.30742049]
[347.           3.87878788]
[348.     3.78]
[349.     3.25]
[350.       3.9375]
[351.           3.75728155]
[352.           3.47931034]
[353.           3.91666667]
[354.          3.5862069]
[355.           3.44630072]
[356.           4.38095238]
[357.           3.29310345]
[358.           3.847222

[652.           2.88636364]
[653.           4.14285714]
[654.           3.43243243]
[655.           2.73300971]
[656.          3.8700565]
[657.           4.01694915]
[658.           3.09677419]
[659.    3.7]
[660.          3.0170697]
[661.           4.64788732]
[662.           3.14173228]
[663.           3.58035714]
[664.           4.02531646]
[665.    3.5]
[666.           3.89320388]
[667.           3.09356725]
[668.           3.58333333]
[669.           3.84725537]
[670.           3.24444444]
[671.           4.25925926]
[672.           3.87234043]
[673.           3.13151365]
[674.           4.27848101]
[675.           3.30952381]
[676.           3.12820513]
[677.           3.89268293]
[678.           3.67767768]
[679.           3.92682927]
[680.           3.57142857]
[681.           4.23684211]
[682.           4.73333333]
[683.          3.5862069]
[684.           3.89473684]
[685.           3.23571429]
[686.           3.77777778]
[687.           3.48734177]
[688.     3.75]
[689.     

[965.           4.11688312]
[966.           3.56363636]
[967.           3.53846154]
[968.           4.13114754]
[969.           4.11538462]
[970.           3.14936248]
[971.           3.33183857]
[972.           3.37142857]
[973.           3.39631336]
[974.           3.73333333]
[975.           3.25990099]
[976.           3.36363636]
[977.       3.7625]
[978.           3.88636364]
[979.           4.04054054]
[980.           3.22222222]
[981.           3.33039648]
[982.           4.17647059]
[983.           4.11538462]
[984.           3.54178674]
[985.           4.21232877]
[986.           3.77272727]
[987.           4.01704545]
[988.           3.84931507]
[989.           4.68181818]
[990.           3.54901961]
[991.     3.75]
[992.           3.41935484]
[993.           3.34482759]
[994.           4.15384615]
[995.           3.89795918]
[996.           3.93581081]
[997.           3.93333333]
[998.           4.11851852]
[999.          3.1868932]
[1000.            4.13095238]
[1001.      

[1266.           3.3415978]
[1267.     3.6]
[1268.            4.25742574]
[1269.      4.25]
[1270.            3.03448276]
[1271.            4.28235294]
[1272.            3.53521127]
[1273.            3.98203593]
[1274.            3.84940778]
[1275.            4.46666667]
[1276.            4.15584416]
[1277.            3.67567568]
[1278.    4.]
[1279.            2.95844875]
[1280.      3.72]
[1281.            3.47916667]
[1282.           4.0952381]
[1283.            3.34782609]
[1284.            3.42209073]
[1285.            3.90646853]
[1286.     3.5]
[1287.            3.94680851]
[1288.            3.75968992]
[1289.            4.30769231]
[1290.            4.18181818]
[1291.            3.80212014]
[1292.            3.39583333]
[1293.            3.42647059]
[1294.            3.92720307]
[1295.       3.575]
[1296.            3.89583333]
[1297.            3.44558522]
[1298.            3.82736156]
[1299.            3.79059829]
[1300.            3.48192771]
[1301.            3.77441077]
[1

[1579.           3.4496732]
[1580.            3.54054054]
[1581.           3.2195122]
[1582.            3.63636364]
[1583.            3.73076923]
[1584.            3.32537961]
[1585.            3.60714286]
[1586.            4.42409639]
[1587.            3.33212996]
[1588.            4.17021277]
[1589.            3.77777778]
[1590.    4.]
[1591.            4.34076433]
[1592.            3.62091503]
[1593.            3.03883495]
[1594.            3.72789116]
[1595.            4.04511278]
[1596.            3.56521739]
[1597.            3.55652174]
[1598.            3.49456522]
[1599.            3.30181818]
[1600.            3.43147208]
[1601.            3.90731707]
[1602.     4.1]
[1603.            3.84285714]
[1604.            4.16666667]
[1605.            3.31224066]
[1606.            3.79126214]
[1607.            3.18478261]
[1608.            2.08333333]
[1609.            3.42061281]
[1610.            3.96428571]
[1611.            3.57374101]
[1612.            3.65217391]
[1613.        

[1870.            3.79746835]
[1871.            3.72649573]
[1872.            3.81818182]
[1873.            3.48989899]
[1874.         3.59375]
[1875.            3.61538462]
[1876.            3.45454545]
[1877.           3.1292517]
[1878.            3.65060241]
[1879.            3.93155894]
[1880.            3.34450262]
[1881.            4.33333333]
[1882.            3.78026906]
[1883.            3.33103448]
[1884.            3.86704385]
[1885.            4.15789474]
[1886.            3.92307692]
[1887.       3.384]
[1888.            3.61764706]
[1889.            3.26923077]
[1890.            3.51980198]
[1891.           3.5483871]
[1892.            4.27272727]
[1893.      3.75]
[1894.            4.24418605]
[1895.            4.03488372]
[1896.            4.14975845]
[1897.           3.7108067]
[1898.            3.92307692]
[1899.            3.79232804]
[1900.       3.675]
[1901.            4.17333333]
[1902.            3.64728682]
[1903.            4.02030457]
[1904.            3.2670

[2169.            3.81081081]
[2170.            4.23015873]
[2171.            4.44554455]
[2172.            3.05986696]
[2173.            3.77104377]
[2174.            3.58426966]
[2175.            4.13609467]
[2176.            4.21787709]
[2177.            3.62068966]
[2178.            4.28735632]
[2179.            3.26712329]
[2180.            2.83863081]
[2181.            3.33224044]
[2182.            3.66666667]
[2183.            3.68571429]
[2184.            4.23333333]
[2185.            4.27645051]
[2186.            3.44178082]
[2187.            3.72992701]
[2188.            3.05679012]
[2189.     3.6]
[2190.            3.89230769]
[2191.            3.18421053]
[2192.            3.82644628]
[2193.    4.]
[2194.            2.86915888]
[2195.            3.41472868]
[2196.            3.97222222]
[2197.            4.10714286]
[2198.            3.64179104]
[2199.            3.06976744]
[2200.            3.10526316]
[2201.            4.35384615]
[2202.            3.28169014]
[2203.    

[2476.            4.16393443]
[2477.            4.47540984]
[2478.            3.55052265]
[2479.            3.84848485]
[2480.            3.86666667]
[2481.            3.90909091]
[2482.     3.5]
[2483.     3.9]
[2484.            3.36928702]
[2485.            3.67073171]
[2486.            3.80519481]
[2487.           3.7027027]
[2488.     4.2]
[2489.            3.39798489]
[2490.            3.54545455]
[2491.            3.03508772]
[2492.            3.76404494]
[2493.            3.53488372]
[2494.    3.]
[2495.            3.48717949]
[2496.            2.99021526]
[2497.            4.50413223]
[2498.            3.16883117]
[2499.            3.61702128]
[2500.            3.63571429]
[2501.            3.90588235]
[2502.           3.9047619]
[2503.      3.02]
[2504.            3.55813953]
[2505.         4.09375]
[2506.            3.35458167]
[2507.            3.94412107]
[2508.            3.56666667]
[2509.            3.34146341]
[2510.            4.53488372]
[2511.            4.20689655]


[2790.            4.24590164]
[2791.        4.5625]
[2792.            2.94764398]
[2793.            4.06844106]
[2794.            3.83216783]
[2795.      3.62]
[2.79600000e+03 2.50990099e+00]
[2797.    3.]
[2798.            4.06493506]
[2799.            4.13043478]
[2800.            3.46153846]
[2801.            3.17821782]
[2802.     3.6]
[2803.            3.79279279]
[2804.            3.88888889]
[2805.            3.89772727]
[2806.            3.30379747]
[2807.            3.39104478]
[2808.            4.11510791]
[2809.            4.33944954]
[2810.            3.46882793]
[2811.            3.66666667]
[2812.            3.60330579]
[2813.    3.]
[2814.            4.04705882]
[2815.            3.69090909]
[2816.            3.81818182]
[2817.            4.20731707]
[2818.           3.6109215]
[2819.     3.9]
[2820.            2.96420582]
[2821.            3.63333333]
[2822.            3.72580645]
[2823.            2.91489362]
[2824.            3.92741935]
[2825.            3.95927602]


[3091.      3.75]
[3092.            4.01886792]
[3093.            3.79888268]
[3094.            3.65853659]
[3095.            3.89655172]
[3096.            4.10659898]
[3097.            3.63492063]
[3098.            3.36956522]
[3099.            3.28301887]
[3100.     4.2]
[3101.            4.14814815]
[3102.            3.44117647]
[3103.            4.12820513]
[3104.            3.89655172]
[3105.            3.99166667]
[3106.            4.16176471]
[3107.            3.55555556]
[3108.            3.68801653]
[3109.            3.52631579]
[3110.            3.60333333]
[3111.            3.24193548]
[3112.            3.38967136]
[3113.      3.68]
[3114.            3.34285714]
[3115.            3.41666667]
[3116.            3.63529412]
[3117.           4.2972973]
[3118.            3.54385965]
[3119.            3.37777778]
[3120.            3.62162162]
[3121.            3.46863469]
[3.12200000e+03 3.11111111e+00]
[3123.            3.56129032]
[3124.            3.42307692]
[3125.            

[3.38500000e+03 3.33333333e+00]
[3386.            3.70945946]
[3.38700000e+03 3.37956204e+00]
[3388.            3.66666667]
[3.38900000e+03 2.82692308e+00]
[3390.            4.18719212]
[3391.            3.72039474]
[3392.     3.8]
[3393.            3.54307116]
[3394.            3.89263804]
[3395.            3.69642857]
[3396.            3.82608696]
[3397.            4.06896552]
[3398.     3.6]
[3399.            3.54545455]
[3400.            4.05963303]
[3.40100000e+03 2.95221027e+00]
[3402.            3.84242424]
[3403.            4.14146341]
[3404.            3.80769231]
[3405.            4.12195122]
[3406.            4.04878049]
[3407.     3.5]
[3408.            3.76724138]
[3409.            4.20454545]
[3.41000000e+03 3.21751026e+00]
[3.41100000e+03 2.73219373e+00]
[3412.            4.15699659]
[3413.            4.11023622]
[3414.           4.0976431]
[3415.            4.01204819]
[3416.           3.5787234]
[3417.            3.86956522]
[3418.            3.79146919]
[3419.        

[3.67200000e+03 3.32019704e+00]
[3673.            3.89622642]
[3674.            3.74725275]
[3.67500000e+03 3.48763251e+00]
[3.67600000e+03 3.63366337e+00]
[3677.            3.95035461]
[3.67800000e+03 3.20143885e+00]
[3.6790e+03 3.5625e+00]
[3680.            3.89285714]
[3681.           3.8742515]
[3682.            4.46153846]
[3.6830000e+03 3.0950764e+00]
[3684.            4.28057554]
[3685.            4.06840391]
[3686.     4.4]
[3.68700000e+03 3.07853403e+00]
[3688.            4.45723684]
[3.68900000e+03 2.95575221e+00]
[3.69000000e+03 2.93017456e+00]
[3.69100000e+03 3.66556291e+00]
[3692.            3.98591549]
[3.69300000e+03 3.45302013e+00]
[3694.            3.96226415]
[3695.            3.99006623]
[3696.      3.94]
[3697.            4.02941176]
[3.698e+03 3.000e+00]
[3699.            4.60655738]
[3700.            3.96969697]
[3701.      3.75]
[3702.            3.78723404]
[3.703e+03 3.300e+00]
[3704.            4.44292237]
[3.70500000e+03 3.70454545e+00]
[3706.            4.11

[3.95200000e+03 3.89655172e+00]
[3.95300000e+03 3.61538462e+00]
[3.95400000e+03 3.44186047e+00]
[3.95500000e+03 3.44078947e+00]
[3.95600000e+03 3.90909091e+00]
[3.95700000e+03 3.88319088e+00]
[3.9580000e+03 3.6402439e+00]
[3.959e+03 2.640e+00]
[3960.            4.17857143]
[3.96100000e+03 3.49565217e+00]
[3.96200000e+03 3.47142857e+00]
[3963.            4.02625821]
[3.964e+03 3.875e+00]
[3.96500000e+03 3.84827586e+00]
[3.96600000e+03 3.73584906e+00]
[3.96700000e+03 2.72197309e+00]
[3.96800000e+03 3.71764706e+00]
[3.969e+03 3.500e+00]
[3.97000000e+03 3.31620553e+00]
[3.97100000e+03 3.48369565e+00]
[3.972e+03 3.520e+00]
[3.97300000e+03 3.67032967e+00]
[3.97400000e+03 3.84552846e+00]
[3.97500000e+03 3.66304348e+00]
[3.97600000e+03 3.62541806e+00]
[3.97700000e+03 3.86666667e+00]
[3978.            4.41666667]
[3979.           4.1443299]
[3.98e+03 2.95e+00]
[3.98100000e+03 3.55760369e+00]
[3.98200000e+03 3.59756098e+00]
[3.98300000e+03 3.38461538e+00]
[3.98400000e+03 3.66153846e+00]
[3.98500

[4.244e+03 3.550e+00]
[4.24500000e+03 3.63043478e+00]
[4.24600000e+03 3.77777778e+00]
[4.24700000e+03 3.13157895e+00]
[4.24800000e+03 3.76470588e+00]
[4.24900000e+03 3.23300971e+00]
[4.2500000e+03 3.9235474e+00]
[4.25100000e+03 3.56701031e+00]
[4.25200000e+03 3.25714286e+00]
[4.25300000e+03 3.41715976e+00]
[4254.            4.41666667]
[4.25500000e+03 4.12195122e+00]
[4.25600000e+03 3.85185185e+00]
[4.25700000e+03 3.28057554e+00]
[4.258e+03 3.715e+00]
[4.25900000e+03 3.66666667e+00]
[4.26000000e+03 3.14506173e+00]
[4.26100000e+03 3.18772563e+00]
[4.26200000e+03 3.65789474e+00]
[4.26300000e+03 3.65789474e+00]
[4.26400000e+03 4.23809524e+00]
[4.26500000e+03 3.85645933e+00]
[4.26600000e+03 3.24637681e+00]
[4.26700000e+03 3.37837838e+00]
[4.26800000e+03 3.26451613e+00]
[4.26900000e+03 3.77092511e+00]
[4.27000000e+03 3.45833333e+00]
[4.27100000e+03 2.99429658e+00]
[4.27200000e+03 3.46017699e+00]
[4273.            4.66666667]
[4.27400000e+03 2.88235294e+00]
[4.27500000e+03 3.80645161e+00]
[4

[4.52600000e+03 3.62352941e+00]
[4.527e+03 3.800e+00]
[4.52800000e+03 3.30645161e+00]
[4.52900000e+03 3.85106383e+00]
[4.53000000e+03 3.60714286e+00]
[4.53100000e+03 3.42798354e+00]
[4.53200000e+03 3.96899225e+00]
[4.53300000e+03 3.80701754e+00]
[4.5340000e+03 3.7012987e+00]
[4.53500000e+03 3.99456522e+00]
[4.53600000e+03 4.23529412e+00]
[4.537e+03 3.840e+00]
[4.538e+03 3.025e+00]
[4.53900000e+03 1.81512605e+00]
[4.54000000e+03 3.71014493e+00]
[4.54100000e+03 2.58108108e+00]
[4.54200000e+03 3.82142857e+00]
[4.54300000e+03 3.29809524e+00]
[4.54400000e+03 3.91666667e+00]
[4.54500000e+03 3.96666667e+00]
[4.546e+03 4.160e+00]
[4.547e+03 2.800e+00]
[4.548e+03 3.000e+00]
[4.549e+03 3.320e+00]
[4.55000000e+03 3.46428571e+00]
[4.55100000e+03 4.02439024e+00]
[4.55200000e+03 3.60869565e+00]
[4.55300000e+03 3.25454545e+00]
[4.55400000e+03 3.47619048e+00]
[4.55500000e+03 3.30337079e+00]
[4.55600000e+03 3.38461538e+00]
[4.55700000e+03 3.62790698e+00]
[4.55800000e+03 4.23809524e+00]
[4.55900000e+03 

[4.82300000e+03 3.33829787e+00]
[4.82400000e+03 3.77092511e+00]
[4.82500000e+03 3.93877551e+00]
[4.82600000e+03 3.75460123e+00]
[4.827e+03 3.375e+00]
[4.828e+03 3.620e+00]
[4.82900000e+03 3.78018576e+00]
[4.83000000e+03 3.53508772e+00]
[4.83100000e+03 4.10126582e+00]
[4.83200000e+03 3.77099237e+00]
[4.83300000e+03 4.03703704e+00]
[4.83400000e+03 3.62857143e+00]
[4.83500000e+03 3.72289157e+00]
[4.83600000e+03 3.47692308e+00]
[4.83700000e+03 3.27439024e+00]
[4.83800000e+03 3.82051282e+00]
[4.83900000e+03 3.04347826e+00]
[4.84000000e+03 3.73611111e+00]
[4.84100000e+03 3.64130435e+00]
[4.842e+03 4.000e+00]
[4.84300000e+03 4.06896552e+00]
[4.84400000e+03 3.96551724e+00]
[4.84500000e+03 3.94117647e+00]
[4.846e+03 3.500e+00]
[4.84700000e+03 4.01388889e+00]
[4.84800000e+03 3.85185185e+00]
[4.84900000e+03 3.99363057e+00]
[4.85e+03 4.00e+00]
[4.85100000e+03 3.66666667e+00]
[4.85200000e+03 3.76131687e+00]
[4.85300000e+03 4.10526316e+00]
[4.85400000e+03 3.79878049e+00]
[4.85500000e+03 3.02283105e+

[5.11300000e+03 2.54212454e+00]
[5.11400000e+03 3.76510067e+00]
[5.115e+03 4.375e+00]
[5.11600000e+03 4.33333333e+00]
[5.11700000e+03 3.14285714e+00]
[5.118e+03 3.050e+00]
[5.11900000e+03 3.91666667e+00]
[5.12000000e+03 3.75647668e+00]
[5.12100000e+03 3.45061728e+00]
[5.12200000e+03 4.47826087e+00]
[5.12300000e+03 3.28431373e+00]
[5.12400000e+03 3.52985075e+00]
[5.12500000e+03 4.23529412e+00]
[5.12600000e+03 3.96478873e+00]
[5.12700000e+03 3.19607843e+00]
[5.12800000e+03 3.86315789e+00]
[5.12900000e+03 3.79090909e+00]
[5.13000000e+03 4.39285714e+00]
[5.1310000e+03 3.4035533e+00]
[5.13200000e+03 4.34482759e+00]
[5.13300000e+03 3.07692308e+00]
[5.13400000e+03 3.71578947e+00]
[5.13500000e+03 3.87012987e+00]
[5.13600000e+03 3.74766355e+00]
[5.13700000e+03 4.12931034e+00]
[5.13800000e+03 3.25308642e+00]
[5.13900000e+03 3.53174603e+00]
[5.14000000e+03 3.39946381e+00]
[5.14100000e+03 3.97674419e+00]
[5.14200000e+03 3.57492355e+00]
[5.14300000e+03 4.01680672e+00]
[5.1440e+03 3.8125e+00]
[5.145

[5.40600000e+03 3.35245902e+00]
[5.40700000e+03 4.22222222e+00]
[5.40800000e+03 4.05882353e+00]
[5.40900000e+03 3.23809524e+00]
[5.41000000e+03 3.52173913e+00]
[5.41100000e+03 2.83333333e+00]
[5.41200000e+03 3.85971223e+00]
[5.41300000e+03 4.18181818e+00]
[5.4140000e+03 3.7721519e+00]
[5.41500000e+03 3.50909091e+00]
[5.41600000e+03 4.20833333e+00]
[5.417e+03 3.200e+00]
[5.418e+03 3.632e+00]
[5.41900000e+03 3.75280899e+00]
[5.42000000e+03 2.65714286e+00]
[5.4210e+03 3.8875e+00]
[5.42200000e+03 3.73714286e+00]
[5.42300000e+03 4.04081633e+00]
[5.42400000e+03 3.80740741e+00]
[5.42500000e+03 3.80434783e+00]
[5.42600000e+03 3.43581081e+00]
[5.42700000e+03 4.58024691e+00]
[5.42800000e+03 3.97938144e+00]
[5.4290000e+03 3.8671875e+00]
[5.43000000e+03 3.83571429e+00]
[5.43100000e+03 3.95454545e+00]
[5.43200000e+03 3.96721311e+00]
[5.43300000e+03 2.99034483e+00]
[5.43400000e+03 4.00819672e+00]
[5.43500000e+03 4.19565217e+00]
[5.43600000e+03 3.57575758e+00]
[5.43700000e+03 3.65384615e+00]
[5.43800

[5.69800000e+03 3.62857143e+00]
[5.69900000e+03 3.13712375e+00]
[5.70000000e+03 3.94736842e+00]
[5.70100000e+03 3.87394958e+00]
[5.70200000e+03 3.86324786e+00]
[5.70300000e+03 3.95945946e+00]
[5.70400000e+03 4.25806452e+00]
[5.70500000e+03 3.69942197e+00]
[5.70600000e+03 3.86060606e+00]
[5.707e+03 4.260e+00]
[5.708e+03 3.100e+00]
[5.70900000e+03 3.75806452e+00]
[5.71000000e+03 3.54545455e+00]
[5.711e+03 3.550e+00]
[5.71200000e+03 3.60240964e+00]
[5.71300000e+03 3.48387097e+00]
[5.71400000e+03 3.66666667e+00]
[5.71500000e+03 3.69047619e+00]
[5.7160000e+03 3.9245283e+00]
[5.71700000e+03 3.74479167e+00]
[5.71800000e+03 4.08290155e+00]
[5.71900000e+03 3.07692308e+00]
[5.72000000e+03 2.78531073e+00]
[5.721e+03 3.750e+00]
[5.72200000e+03 3.64305177e+00]
[5.72300000e+03 3.43564356e+00]
[5.72400000e+03 4.09278351e+00]
[5.725e+03 3.450e+00]
[5.72600000e+03 3.81756757e+00]
[5.72700000e+03 3.17647059e+00]
[5.72800000e+03 3.46439628e+00]
[5.72900000e+03 4.22580645e+00]
[5.73000000e+03 3.23076923e+

[5.99300000e+03 3.56666667e+00]
[5.99400000e+03 4.32051282e+00]
[5.99500000e+03 3.95698925e+00]
[5.99600000e+03 3.81049069e+00]
[5.99700000e+03 4.40350877e+00]
[5.9980000e+03 3.2721519e+00]
[5.99900000e+03 4.11111111e+00]
[6.00000000e+03 3.24505929e+00]
[6.00100000e+03 3.59401709e+00]
[6.00200000e+03 4.07164179e+00]
[6.00300000e+03 4.10629921e+00]
[6.00400000e+03 3.38596491e+00]
[6.00500000e+03 3.67045455e+00]
[6.00600000e+03 3.16129032e+00]
[6.00700000e+03 3.15337423e+00]
[6.00800000e+03 3.57142857e+00]
[6.00900e+03 3.34375e+00]
[6.01000000e+03 3.97160883e+00]
[6.01100000e+03 3.96954315e+00]
[6.012e+03 3.000e+00]
[6.01300000e+03 4.08064516e+00]
[6.01400000e+03 3.88679245e+00]
[6.01500000e+03 3.75438596e+00]
[6.01600000e+03 3.18921892e+00]
[6.01700000e+03 3.51515152e+00]
[6.01800000e+03 3.59119497e+00]
[6.01900000e+03 3.46067416e+00]
[6.02000000e+03 4.39534884e+00]
[6.021e+03 3.500e+00]
[6.02200000e+03 3.85416667e+00]
[6.02300000e+03 3.68707483e+00]
[6.02400000e+03 4.12631579e+00]
[6.0

In [139]:
# 교수님 정답
list1=[]
for i in user_id :
    #rs = np.mean(data[data[:,0]==i][:,2])
    rs = data[data[ : , 0 ] == i][:, 2].mean()
    list1.append(rs)
list1

[4.188679245283019,
 3.7131782945736433,
 3.9019607843137254,
 4.190476190476191,
 3.1464646464646466,
 3.9014084507042255,
 4.32258064516129,
 3.884892086330935,
 3.7358490566037736,
 4.114713216957606,
 3.2773722627737225,
 3.8260869565217392,
 3.388888888888889,
 3.32,
 3.3233830845771144,
 3.0285714285714285,
 4.075829383886256,
 3.6491803278688524,
 3.5725490196078433,
 4.083333333333333,
 2.909090909090909,
 3.0673400673400675,
 3.3157894736842106,
 3.948529411764706,
 3.7411764705882353,
 2.96,
 4.171428571428572,
 3.7570093457943927,
 3.5833333333333335,
 3.488372093023256,
 3.73109243697479,
 3.625,
 3.498721227621483,
 3.8658536585365852,
 3.54040404040404,
 4.199430199430199,
 3.69811320754717,
 3.58,
 3.564516129032258,
 3.4479166666666665,
 3.48,
 3.74025974025974,
 4.125,
 3.6321243523316062,
 2.946127946127946,
 4.219512195121951,
 3.909090909090909,
 3.068561872909699,
 3.712962962962963,
 3.0697674418604652,
 3.825,
 3.5569620253164556,
 4.2368421052631575,
 4.025,
 4.

In [9]:
# 1.새로운 교수방법 
list1=[]
for i in user_id :
    #rs = np.mean(data[data[:,0]==i][:,2])
    rs = data[data[ : , 0 ] == i][:, 2].mean()
    list1.append([i,rs])
list1

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [10]:
# 2.새로운 교수방법 
result22 = np.array(list1)
result22

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [141]:
# 교수님 정답
u_m=np.array(list1)
u_m

array([4.18867925, 3.71317829, 3.90196078, ..., 3.8       , 3.87804878,
       3.57771261])

In [145]:
# 교수님 정답
list2=[]
for i in user_id :
    list2.append([i,list1[i-1]])
list2

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [146]:
# 최종 사용자별 평점평균
# 교수님 정답
result = np.array(list2)
result

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [138]:
# 블리언 인덱싱 이용해서 평균 평점이 4점 이상인 사용자만 구하기
# 내 방법
for i in user_id :
    #rs = np.mean(data[data[:,0]==i][:,2])
    rs1 = data[data[ : , 0 ] == i][:, 2].mean()
    if rs1 >= 4 :
        rs3 = np.array([i,rs1])
        print(rs3)
        

[1.         4.18867925]
[4.         4.19047619]
[7.         4.32258065]
[10.          4.11471322]
[17.          4.07582938]
[20.          4.08333333]
[27.          4.17142857]
[36.         4.1994302]
[43.     4.125]
[46.         4.2195122]
[53.          4.23684211]
[54.     4.025]
[55.    4.12]
[64.          4.14814815]
[65.          4.34710744]
[67.        4.296875]
[69.          4.15384615]
[74.          4.04651163]
[75.          4.00571429]
[76.          4.17241379]
[81.          4.41860465]
[82.          4.01694915]
[86.      4.3125]
[88.          4.14705882]
[91.          4.70454545]
[97.          4.47402597]
[101.           4.67924528]
[103.           4.05217391]
[105.           4.29508197]
[106.          4.0212766]
[109.   4.]
[112.           4.18333333]
[121.           4.41666667]
[124.           4.17391304]
[125.           4.09859155]
[126.   4.]
[128.           4.36363636]
[129.           4.02531646]
[130.           4.31111111]
[138.           4.49230769]
[150.           4.02

[1234.            4.29166667]
[1241.            4.24742268]
[1245.            4.33333333]
[1250.            4.19047619]
[1252.            4.02542373]
[1254.            4.11818182]
[1256.         4.34375]
[1258.            4.26190476]
[1268.            4.25742574]
[1269.      4.25]
[1271.            4.28235294]
[1275.            4.46666667]
[1276.            4.15584416]
[1278.    4.]
[1282.           4.0952381]
[1289.            4.30769231]
[1290.            4.18181818]
[1302.            4.26666667]
[1305.            4.33333333]
[1306.            4.14750542]
[1307.            4.33333333]
[1315.            4.50537634]
[1320.            4.01709402]
[1322.           4.1171875]
[1324.            4.03703704]
[1330.            4.26086957]
[1336.            4.08695652]
[1338.            4.03030303]
[1343.            4.41577061]
[1349.            4.65116279]
[1351.     4.2]
[1355.            4.16981132]
[1361.            4.13533835]
[1363.            4.38095238]
[1364.    4.]
[1368.            

[2523.            4.00769231]
[2527.            4.14285714]
[2532.            4.09677419]
[2543.            4.45833333]
[2545.            4.09803922]
[2547.            4.14388489]
[2553.            4.13043478]
[2554.            4.02380952]
[2560.       4.125]
[2571.            4.07352941]
[2572.            4.18543046]
[2573.            4.01030928]
[2574.            4.60606061]
[2578.            4.14285714]
[2579.            4.16176471]
[2581.            4.05210918]
[2582.    4.]
[2583.            4.34138973]
[2586.            4.12244898]
[2587.            4.03225806]
[2593.            4.53676471]
[2606.      4.22]
[2607.            4.17741935]
[2608.            4.00877193]
[2609.            4.30693069]
[2613.            4.09090909]
[2614.            4.13333333]
[2619.            4.23655914]
[2624.            4.14705882]
[2626.            4.04545455]
[2629.            4.01102941]
[2631.            4.26966292]
[2641.            4.09748428]
[2646.            4.13043478]
[2647.            

[3611.            4.02926829]
[3629.            4.16129032]
[3633.    4.]
[3635.            4.20858896]
[3644.            4.02439024]
[3646.            4.13978495]
[3649.            4.25490196]
[3653.            4.20720721]
[3657.            4.15789474]
[3659.         4.21875]
[3666.            4.14285714]
[3671.            4.20192308]
[3682.            4.46153846]
[3684.            4.28057554]
[3685.            4.06840391]
[3686.     4.4]
[3688.            4.45723684]
[3697.            4.02941176]
[3699.            4.60655738]
[3704.            4.44292237]
[3706.            4.11538462]
[3711.            4.19318182]
[3723.            4.25641026]
[3738.         4.53125]
[3740.            4.27659574]
[3744.            4.08333333]
[3747.         4.03125]
[3755.            4.47222222]
[3757.            4.26368159]
[3759.            4.00970874]
[3761.           4.1871345]
[3765.    4.]
[3769.           4.2902439]
[3770.           4.0037594]
[3774.    4.]
[3780.      4.24]
[3781.            

[4.80900000e+03 4.01685393e+00]
[4.81100000e+03 4.11904762e+00]
[4.81300000e+03 4.18269231e+00]
[4.81500000e+03 4.40540541e+00]
[4.81600000e+03 4.22311828e+00]
[4.81700000e+03 4.38043478e+00]
[4.83100000e+03 4.10126582e+00]
[4.83300000e+03 4.03703704e+00]
[4.842e+03 4.000e+00]
[4.84300000e+03 4.06896552e+00]
[4.84700000e+03 4.01388889e+00]
[4.85e+03 4.00e+00]
[4.85300000e+03 4.10526316e+00]
[4.85800000e+03 4.04424779e+00]
[4.85900000e+03 4.23255814e+00]
[4.86400000e+03 4.18181818e+00]
[4.86600000e+03 4.02666667e+00]
[4.871e+03 4.000e+00]
[4.87300000e+03 4.21428571e+00]
[4.87400000e+03 4.38709677e+00]
[4.87600000e+03 4.05555556e+00]
[4.88200000e+03 4.02955665e+00]
[4.88500000e+03 4.46666667e+00]
[4.88800000e+03 4.34448161e+00]
[4.88900000e+03 4.34732824e+00]
[4.89500000e+03 4.13235294e+00]
[4.89800000e+03 4.16736402e+00]
[4.90000000e+03 4.08695652e+00]
[4.90300000e+03 4.01818182e+00]
[4.90400000e+03 4.56188119e+00]
[4.912e+03 4.000e+00]
[4.91900000e+03 4.08108108e+00]
[4.92e+03 4.06e+00

[5.82300000e+03 4.01904762e+00]
[5.82500000e+03 4.03389831e+00]
[5.83200000e+03 4.05128205e+00]
[5.83500000e+03 4.22580645e+00]
[5.8390000e+03 4.5483871e+00]
[5.84100000e+03 4.14371257e+00]
[5.84200000e+03 4.03846154e+00]
[5.84500000e+03 4.27555556e+00]
[5.84600000e+03 4.16129032e+00]
[5.84700000e+03 4.00842697e+00]
[5.85100000e+03 4.01234568e+00]
[5.85500000e+03 4.03921569e+00]
[5.858e+03 4.070e+00]
[5.859e+03 4.000e+00]
[5.862e+03 4.600e+00]
[5.86400000e+03 4.20512821e+00]
[5.86800000e+03 4.13432836e+00]
[5.871e+03 4.170e+00]
[5.87300000e+03 4.24242424e+00]
[5.88500000e+03 4.08264463e+00]
[5.8920000e+03 4.0877193e+00]
[5.90800000e+03 4.12135922e+00]
[5.9180000e+03 4.2173913e+00]
[5.93000000e+03 4.36170213e+00]
[5.93300000e+03 4.24390244e+00]
[5.934e+03 4.000e+00]
[5.93600000e+03 4.61111111e+00]
[5.93900000e+03 4.04504505e+00]
[5.94200000e+03 4.02873563e+00]
[5.94300000e+03 4.07692308e+00]
[5.94500000e+03 4.17647059e+00]
[5.94800000e+03 4.23115578e+00]
[5.9520000e+03 4.3255814e+00]
[5

In [149]:
# 블리언 인덱싱 이용해서 평균 평점이 4점 이상인 사용자만 구하기
# 교수님 정답

up4 =result[result[:,1]>=4]
up4

array([[1.00000000e+00, 4.18867925e+00],
       [4.00000000e+00, 4.19047619e+00],
       [7.00000000e+00, 4.32258065e+00],
       ...,
       [6.02700000e+03, 4.25000000e+00],
       [6.03200000e+03, 4.13461538e+00],
       [6.03400000e+03, 4.09523810e+00]])

In [159]:
print('전체요소갯수:',up4.size)
print('크기:',up4.shape)
print('배열의 길이:',len(up4))
print('하나의열의요소갯수:',up4[:,0].size)

전체요소갯수: 3088
크기: (1544, 2)
배열의 길이: 1544
하나의열의요소갯수: 1544


In [ ]:
# csv파일로 저장하기
np.savetxt('user_rating.csv',result,delimiter=',',fmt = '%.3f')
      